// <auto-generated />
using System;
using LetsTalk.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LetsTalk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126105251_NomDeLaMigration")]
    partial class NomDeLaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Models.Canaux", b =>
                {
                    b.Property<int>("CanauxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CanauxId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CanauxId");

                    b.HasIndex("ServerId");

                    b.ToTable("canaux", (string)null);
                });

            modelBuilder.Entity("Models.ConversationPriver", b =>
                {
                    b.Property<int>("ConversationPriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConversationPriverId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ConversationPriverId");

                    b.ToTable("ConversationPriver", (string)null);
                });

            modelBuilder.Entity("Models.Fichier", b =>
                {
                    b.Property<int>("FichierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FichierId"));

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FichierId");

                    b.ToTable("fichier", (string)null);
                });

            modelBuilder.Entity("Models.Membre", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UtilisateurId", "ServerId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ServerId");

                    b.ToTable("Membre", (string)null);
                });

            modelBuilder.Entity("Models.MembreMP", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.HasKey("UtilisateurId", "ConversationId");

                    b.HasIndex("ConversationId");

                    b.ToTable("membreMP", (string)null);
                });

            modelBuilder.Entity("Models.MessageCanal", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("CanalId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Epingle")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("CanalId", "DateEnvoi");

                    b.ToTable("messageCanal", (string)null);
                });

            modelBuilder.Entity("Models.MessageLu", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("MessageType")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<bool>("Lu")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UtilisateurId", "MessageType", "MessageId");

                    b.ToTable("messageLu", (string)null);
                });

            modelBuilder.Entity("Models.MessagePriver", b =>
                {
                    b.Property<int>("MessagePriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessagePriverId"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ConversationPriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Epingle")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("MessagePriverId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("ConversationPriverId", "DateEnvoi");

                    b.ToTable("messagePriver", (string)null);
                });

            modelBuilder.Entity("Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<bool>("Lu")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("ServerId");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ServerId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("ServerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("server", (string)null);
                });

            modelBuilder.Entity("Models.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UtilisateurId"));

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProfilPicture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type2Fa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UtilisateurId");

                    b.ToTable("utilisateur", (string)null);
                });

            modelBuilder.Entity("Models.Canaux", b =>
                {
                    b.HasOne("Models.Server", "Server")
                        .WithMany("Canaux")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Models.Membre", b =>
                {
                    b.HasOne("Models.Role", "Role")
                        .WithMany("Membres")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Server", "Server")
                        .WithMany("Membres")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Utilisateur", "Utilisateur")
                        .WithMany("Membres")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Server");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Models.MembreMP", b =>
                {
                    b.HasOne("Models.ConversationPriver", "ConversationPriver")
                        .WithMany("MembreMPs")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Utilisateur", "Utilisateur")
                        .WithMany("MembreMPs")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationPriver");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Models.MessageCanal", b =>
                {
                    b.HasOne("Models.Canaux", "Canal")
                        .WithMany("Messages")
                        .HasForeignKey("CanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Utilisateur", "Utilisateur")
                        .WithMany("MessagesCanal")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canal");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Models.MessageLu", b =>
                {
                    b.HasOne("Models.Utilisateur", "Utilisateur")
                        .WithMany("MessageLus")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Models.MessagePriver", b =>
                {
                    b.HasOne("Models.ConversationPriver", "ConversationPriver")
                        .WithMany("MessagesPriver")
                        .HasForeignKey("ConversationPriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Utilisateur", "Utilisateur")
                        .WithMany("MessagesPriver")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationPriver");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Models.Notification", b =>
                {
                    b.HasOne("Models.Utilisateur", "Utilisateur")
                        .WithMany("Notifications")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.HasOne("Models.Server", "Server")
                        .WithMany("Roles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Models.Server", b =>
                {
                    b.HasOne("Models.Utilisateur", "Owner")
                        .WithMany("OwnedServers")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Models.Canaux", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Models.ConversationPriver", b =>
                {
                    b.Navigation("MembreMPs");

                    b.Navigation("MessagesPriver");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Navigation("Membres");
                });

            modelBuilder.Entity("Models.Server", b =>
                {
                    b.Navigation("Canaux");

                    b.Navigation("Membres");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Models.Utilisateur", b =>
                {
                    b.Navigation("MembreMPs");

                    b.Navigation("Membres");

                    b.Navigation("MessageLus");

                    b.Navigation("MessagesCanal");

                    b.Navigation("MessagesPriver");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedServers");
                });
#pragma warning restore 612, 618
        }
    }
}
